#!/usr/bin/env bash
#Using case statement in a while loop

i=1
while [ $i -le 20 ]
do
	case $i in
		$i == 4 )
			echo "bad luck from China" ;;
		$i == 9 )
			echo "bad luck from Japan" ;;
		$i == 17 )
			echo "bad luck from Italy" ;;
		* )
			echo $i
	esac

	i=$(( i+1 ))
done
